export enum Events{
    CONTAINERS_LIST= "CONTAINERS_LIST",
    CONTAINERS_METRICS ="CONTAINERS_METRICS",
    MEMORY_USAGE= "MEMORY_USAGE",
    DISK_USAGE= "DISK_USAGE",
    DOCKER_ENGINE_INFO= "DOCKER_ENGINE_INFO",
    TEMPERATURE= "TEMPERATURE",
    HEALTH_CHECK="HEALTH_CHECK",
    CONTAINER_START="CONTAINER_START",
    CONTAINER_RESTART="CONTAINER_RESTART",
    CONTAINER_STOP="CONTAINER_STOP",
    CONTAINER_DELETE="CONTAINER_DELETE",
    CONTAINER_DETAILS="CONTAINER_DETAILS",
    DOCKER_RUN_IMAGE="DOCKER_RUN_IMAGE",
    CPU_USAGE= "CPU_USAGE"
}