export enum SocketEvents{
    CONTAINERS_LIST= "CONTAINERS_LIST",
    CONTAINERS_METRICS ="CONTAINERS_METRICS",
    MEMORY_USAGE= "MEMORY_USAGE",
    DISK_USAGE= "DISK_USAGE",
    DOCKER_ENGINE_INFO= "DOCKER_ENGINE_INFO",
    TEMPERATURE= "TEMPERATURE",
    HEALTH_CHECK="HEALTH_CHECK"
}