FROM node:12.13-alpine As development
RUN apt-get update && apt-get install -y build-essential && apt-get install -y python
WORKDIR /usr/src/app

COPY package*.json ./
COPY build.tar.gz ./
RUN npm install --only=development

COPY . .

RUN npm run build

FROM node:12.13-alpine as production
RUN apt-get update && apt-get install -y build-essential && apt-get install -y python
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./
COPY build.tar.gz ./
RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]